version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  express-job:
    working_directory: ~/express-work/express
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout:
          path: ~/express-work
      - run:
          name: 'if change express'
          command: |
            if ! is_changed_directory.sh express main ; then
              echo "express に変更がありません"
              circleci step halt
            fi
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: yarn install
      - run: yarn test
  fastify-job:
    working_directory: ~/express-work/fastify
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout:
          path: ~/express-work
      - run:
          name: 'if change fastify'
          command: |
            if ! is_changed_directory.sh fastify main ; then
              echo "fastify に変更がありません"
              circleci step halt
            fi
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: yarn install
      - run: yarn test

workflows:
  test:
    jobs:
      - express-job
      - fastify-job
