version: 2.1

orbs:
  node: circleci/node@5.0.0

executors:
  basic-executor:
    docker:
      - image: 'cimg/base:stable'

commands:
  stop-if-no-change-directory:
    description: 'ディレクトリに変更がなければ停止する'
    parameters:
      directory:
        type: string
      branch:
        type: string
        default: "origin/main"
    steps:
      - run:
          command: |
            if ! ../.circleci/is_changed_directories.sh << parameters.directory >> << parameters.branch >> ; then
              circleci step halt
            fi

jobs:
  express-job:
    executor: basic-executor
    working_directory: ~/express-work/express
    steps:
      - checkout:
          path: ~/express-work
      - stop-if-no-change-directory:
          directory: "express"
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: yarn install
      - run: yarn test
  fastify-job:
    executor: basic-executor
    working_directory: ~/express-work/fastify
    steps:
      - checkout:
          path: ~/express-work
      - stop-if-no-change-directory:
          directory: "fastify"
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: yarn install
      - run: yarn test

workflows:
  test:
    jobs:
      - express-job
      - fastify-job
